### ISSUE TITLE
Unable to install SEB server

### ISSUE THREAD

**Issue by shychowd** [SafeExamBrowser/seb-server-setup#15]
**Describe the bug**
Server shutting down without reporting error

**To Reproduce**
1. Follow provided setup instructions
2. Change port from 8080 to 8090 in spring/application.properties
3. docker compose up

**Expected behavior**
Server should start and remain alive

**Screenshots**

**Setup (please complete the following information):**
-prod/bundled/dockerhub
-OS is red hat enterprise linux
-Server version 1.5.0-64606ec

**Additional context**
Logs:
seb-server          | 19:17:17.262 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> Version: v1.5.0-64606ec
seb-server          | 19:17:17.263 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ---->
seb-server          | 19:17:17.263 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> Active profiles: [gui, ws, prod-ws, prod-gui, prod]
seb-server          | 19:17:17.263 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ---->
seb-server          | 19:17:17.264 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> Context Path: /
seb-server          | 19:17:17.264 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ---->
seb-server          | 19:17:17.264 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> *********************************************************
seb-server          | 19:17:17.264 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> *** GUI Service starting up...                        ***
seb-server          | 19:17:17.264 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> *********************************************************
seb-server          | 19:17:17.264 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ---->
seb-server          | 19:17:17.264 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> Webservice connection: http://localhost:8080/admin-api/v1
seb-server          | 19:17:17.265 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> GUI service internal connection : http://0.0.0.0:8080
seb-server          | 19:17:17.265 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> GUI service external connection : https://sebserver.serco-sgt.dev:8090
seb-server          | 19:17:17.265 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> GUI service endpoint : /gui
seb-server          | 19:17:17.265 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ---->
seb-server          | 19:17:17.265 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> Webservice admin API endpoint: /admin-api/v1
seb-server          | 19:17:17.265 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> Webservice exam API endpoint: /exam-api
seb-server          | 19:17:17.265 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ---->
seb-server          | 19:17:17.266 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> Webservice admin API basic access: --guiClient--
seb-server          | 19:17:17.266 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ---->
seb-server          | 19:17:17.266 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> *********************************************************
seb-server          | 19:17:17.266 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> *** GUI Service successfully successfully started up! ***
seb-server          | 19:17:17.266 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> *********************************************************
seb-server          | 19:17:17.266 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> *********************************************************
seb-server          | 19:17:17.266 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> *** Webservice starting up...                         ***
seb-server          | 19:17:17.266 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> *********************************************************
seb-server          | 19:17:17.267 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ---->
seb-server          | 19:17:17.267 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> Register Webservice: 08ff0483-e0f2-4d23-ad0b-3ee37129e1d5_v1.5.0-64606ec
seb-server          | 19:17:20.344 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] *********************************************************
**seb-server          | 19:17:20.344 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] **** Gracefully Shutdown of SEB Server instance 0.0.0.0
seb-server          | 19:17:20.344 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ---->
seb-server          | 19:17:20.346 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> Unregister Webservice: 08ff0483-e0f2-4d23-ad0b-3ee37129e1d5_v1.5.0-64606ec**

**Comment by anhefti** [comment]
Hi,

If you want to setup SEB Server running on another external port, you need to do this within the reverse proxy setup that comes with the bundled docker setup
Therefore you can leave the application-prod.properties configuration file as it is and do all needed modifications within the docker-compose.yml file like this:

![image](https://github.com/SafeExamBrowser/seb-server-setup/assets/39078777/91e6eca9-8e56-4ac3-9a17-ad0244f0a4fd)

Please add your external URL address information within the settings given in the first red section of the image. If you use HTTPS with proper certificates, then the following "reverse proxy" container will do the TLS termination and is exposed to the host-network while the other containers are in the seb-server-network and only Docker internal.  
If you use another external HTTPS port you can map that within the "reverse proxy" container definition. Not the default HTTPS  443 is set. If you want to map that to 8090, you can use:

```
ports:
      - 8090:443
```

If you don't want to use HTTPS, what we do not recommend since this comes with security issues, you can completely delete the "reverse proxy" container from the configuration and expose the "seb-server" container directly to your needed port by adding:

```
ports:
      - 8090:8080
```

within the "seb-server" container configuration.

Hope this will help you. In the other hand, if you can let us know more about what kind of setup you would like to have or what your goal is, we can provide you more accurate help for setup.
