### ISSUE TITLE
Distributed Environment for SEB server

### ISSUE THREAD

**Issue by ano010** [SafeExamBrowser/seb-server-setup#9]
Hi,

I kindly appreciate any input regarding the following...

**Describe the bug**
I have been trying to set up the SEB server in a Kubernetes environmet to achieve scalability. It is running fine when there is only one instance. Though it fails when I increase the number of instances to two or more. I get a "The server session timed out" error when there is more than one instance.

**To Reproduce**
1. Deploy the SEB server in a distributed environment (I am using AKS)
2. Scale it to have more than one instance
3. Try to access the SEB server

**Expected behavior**
It should work without the server session time out error

**Screenshots**
<img width="924" alt="image" src="https://user-images.githubusercontent.com/33832254/161733528-9812bdfd-20a8-4cda-ba78-523f5d398737.png">

**Setup**
 - Setup specification [production/bundled/dockerhub]
 - IT environment [Azure Kubernetes Services]
 - SEB Server Version [1.2-stable]

**Comment by anhefti** [comment]
Hi,

The session timeout normally applies after a certain amout of time, when the user-session has timed out. If this is the case, it is expected behavior. On the other hand, if the session timeout appears suddenly after login or randomly after some clicks, this might be caused from a incorrect setup. 

If you have setup SEB Server on kubernetes then I expect that you have separated container/posts for your webservice as well as for you gui-service right?
Your setup should look similar to the one in the below image:
![image](https://user-images.githubusercontent.com/39078777/161735835-a603323a-3ddc-4fb0-8dd9-5971e3999063.png)

**Very important are the sticky-sessions on the described load-balancers**. Do you have this in place?
Another point is to set the right env Variables within the gui-service setup as well as for the webservice setup. If you have proper sticky session in place and it don't work, please check your env Variables and make sure your gui-services are communicating with the web-service through  the external load-balancer and the sticky sessions are in place.
